Fix style issue in whoami which broke the sbase-box target
sbase-box.c:(.text+0xd88): undefined reference to `whoami_main'
collect2: ld returned 1 exit status

Broke the sed magic in Makefile.